[package]
name = "google_api_test"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
base64 = "0.22.1"
serde = { version = "1.0", features = ["derive"] }