# This flow runs two AI jobs in parallel and then merges their outputs into a single final report.
apiVersion: ferri.flow/v1alpha1
kind: Flow
metadata:
  name: parallel-ai-analysis-and-merge
spec:
  jobs:
    generate-pros:
      name: "Analyze Advantages of Rust"
      steps:
        - name: "Use Gemini to list the pros"
          run: "ferri with --model gemini-pro --output pros.txt -- 'List and briefly explain three major advantages of programming in Rust.'"

    generate-cons:
      name: "Analyze Disadvantages of Rust"
      steps:
        - name: "Use Gemini to list the cons"
          run: "ferri with --model gemini-pro --output cons.txt -- 'List and briefly explain three major disadvantages or challenges of programming in Rust.'"

    create-report:
      name: "Create Final Report"
      needs:
        - generate-pros
        - generate-cons
      steps:
        - name: "Combine pros and cons into a single markdown file"
          run: |
            echo '# Analysis of Rust: Pros and Cons' > full_report.md
            echo '' >> full_report.md
            echo '## Advantages' >> full_report.md
            cat pros.txt >> full_report.md
            echo '' >> full_report.md
            echo '\n## Disadvantages' >> full_report.md
            cat cons.txt >> full_report.md
            echo '\n\n' >> full_report.md
            echo '---' >> full_report.md
            echo 'Report generated by Ferri AI flow.' >> full_report.md
