# This flow demonstrates the use of the 'workspaces' feature for explicitly managing
# shared data between jobs, preparing it for future containerized runners.
apiVersion: ferri.flow/v1alpha1
kind: Flow
metadata:
  name: workspace-build-and-test-pipeline
spec:
  # Define the shared storage volumes for the entire flow.
  workspaces:
    - name: source-code
    - name: build-artifacts

  jobs:
    build-application:
      name: "Build Application"
      steps:
        - name: "Simulate checkout and compile"
          # This step mounts the two workspaces into its virtual filesystem.
          workspaces:
            - name: source-code
              mountPath: /app/src
            - name: build-artifacts
              mountPath: /app/dist
          run: |
            echo "--- Building Application ---"
            echo "print('hello from my app')" > /app/src/main.py
            echo "Build artifact created at $(date)" > /app/dist/app.bin
            echo "Source code:"
            cat /app/src/main.py
            echo "Build artifact:"
            cat /app/dist/app.bin

    test-application:
      name: "Test Application"
      needs:
        - build-application
      steps:
        - name: "Run tests on the build artifacts"
          # This job mounts the same workspaces, but with different permissions.
          workspaces:
            - name: source-code
              mountPath: /app/src
              readOnly: true # The test job cannot modify the source code.
            - name: build-artifacts
              mountPath: /app/dist
          run: |
            echo "--- Testing Application ---"
            echo "Verifying source code (read-only):"
            cat /app/src/main.py
            echo "Verifying build artifact:"
            cat /app/dist/app.bin
            echo "Test successful!"
