# This flow simulates a multi-language build process where frontend and backend
# assets are built in parallel and placed into a single shared workspace.
apiVersion: ferri.flow/v1alpha1
kind: Flow
metadata:
  name: multi-language-build-and-package
spec:
  workspaces:
    - name: build-output

  jobs:
    build-frontend:
      name: "Build Frontend (e.g., React)"
      steps:
        - name: "Compile JS and CSS"
          workspaces:
            - name: build-output
              mountPath: /dist
          run: |
            echo "--- Building frontend assets ---"
            mkdir -p /dist/static/css
            echo "/* main.css */" > /dist/static/css/main.css
            mkdir -p /dist/static/js
            echo "// app.js" > /dist/static/js/app.js
            echo "index.html" > /dist/index.html
            echo "Frontend build complete."

    build-backend:
      name: "Build Backend (e.g., Rust)"
      steps:
        - name: "Compile Rust binary"
          workspaces:
            - name: build-output
              mountPath: /dist
          run: |
            echo "--- Building backend binary ---"
            echo "#!/bin/sh" > /dist/app.bin
            echo "echo 'Backend server running'" >> /dist/app.bin
            chmod +x /dist/app.bin
            echo "Backend build complete."

    package-application:
      name: "Package Final Application"
      needs:
        - build-frontend
        - build-backend
      steps:
        - name: "Verify contents and create tarball"
          workspaces:
            - name: build-output
              mountPath: /app
          run: |
            echo "--- Packaging application ---"
            echo "Final directory structure:"
            ls -R /app
            echo ""
            echo "Creating package.tar.gz..."
            # In a real runner, we'd use tar
            # tar -czf /app/package.tar.gz -C /app .
            echo "Tarball created."
            echo "Packaging complete."
