# Example ferri-flow.yml demonstrating the new schema specification
# This is a simple CI/CD pipeline that builds, tests, and deploys a project

apiVersion: ferri.flow/v1alpha1
kind: Flow

metadata:
  name: example-pipeline
  labels:
    environment: dev
    version: v1
  annotations:
    description: "Example CI/CD pipeline demonstrating ferri flow features"

spec:
  # Input parameters that can be passed at runtime
  inputs:
    environment:
      type: string
      description: "Deployment environment (staging or production)"
      default: "staging"
    skip_tests:
      type: boolean
      description: "Skip test execution"
      default: false

  # Shared workspaces for file I/O between jobs
  workspaces:
    - name: source-code
    - name: build-artifacts

  # Jobs define the workflow steps
  jobs:
    # Checkout job - runs first (no dependencies)
    checkout:
      name: "Checkout Source"
      runs-on: ubuntu-latest
      steps:
        - id: clone
          name: "Clone repository"
          run: echo "Cloning source code..."
          env:
            GIT_BRANCH: "main"

    # Build job - depends on checkout
    build:
      name: "Build Application"
      runs-on: ubuntu-latest
      needs: [checkout]
      steps:
        - name: "Compile code"
          run: echo "Building application..."

        - name: "Package artifacts"
          run: echo "Creating build artifacts..."

    # Test job - runs in parallel with build (both depend on checkout)
    test:
      name: "Run Tests"
      runs-on: ubuntu-latest
      needs: [checkout]
      steps:
        - name: "Unit tests"
          run: echo "Running unit tests..."

        - name: "Integration tests"
          run: echo "Running integration tests..."

    # Deploy job - waits for both build and test to complete
    deploy:
      name: "Deploy Application"
      runs-on: ubuntu-latest
      needs: [build, test]
      steps:
        - name: "Deploy to environment"
          run: echo "Deploying to ${{ ctx.inputs.environment }}"
          env:
            DEPLOY_ENV: "${{ ctx.inputs.environment }}"

        - name: "Verify deployment"
          run: echo "Verifying deployment..."

# To run this flow:
#   ferri flow show examples/example-flow.yml
#   ferri flow run examples/example-flow.yml

# To pass inputs:
#   ferri flow run examples/example-flow.yml --input environment=production
