[package]
name = "ferri-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
magic-crypt = "3.1.13"

[dev-dependencies]
tempfile = "3.10.1"